import { LegalLinks } from "../legal-links";
import { displayEnvironment, FAULTCITE_RELEASE } from "../../lib/release";

export const metadata = { title: "Pilot Privacy Notice" };

export default function PrivacyPage() {
  const environment = displayEnvironment(process.env.FAULTCITE_ENVIRONMENT);
  return <main className="policy-page"><article><span className="eyebrow">CONTROLLED PILOT</span><h1>Pilot privacy notice</h1><p className="policy-lead">This notice describes the information FaultCite handles during a company-authorized controlled pilot. The signed pilot agreement controls if it says something different.</p><h2>Information handled</h2><ul><li>Clerk account identity and verified work email.</li><li>Company, team-role, machine, case, observation, approval, and audit records.</li><li>Manuals and evidence files deliberately uploaded by authorized users.</li><li>Operational security information needed to protect and troubleshoot the service.</li></ul><h2>Service providers</h2><p>FaultCite uses Clerk for authentication, Cloudflare Workers/D1/R2 for application hosting and storage, and Resend for invitation email delivery. No subscription billing is implemented in this release.</p><h2>Company responsibilities</h2><p>Use only company-authorized pilot data. Do not upload unnecessary personal information, credentials, export-controlled material, or information your company is not permitted to share. Image files may contain device metadata; remove sensitive metadata before uploading when required by company policy.</p><h2>Retention, access, and deletion</h2><p>Retention, export, correction, and deletion instructions must be agreed with the pilot company before production data is accepted. Managers can export company records; account-level backup and deletion operations remain controlled by the service owner.</p><h2>Questions</h2><p>Contact the FaultCite pilot coordinator named in your written pilot agreement. Never send passwords, invitation links, authorization tokens, or maintenance evidence through an unapproved support channel.</p></article><LegalLinks version={FAULTCITE_RELEASE} environment={environment} /></main>;
}
