import { LegalLinks } from "../legal-links";
import { displayEnvironment, FAULTCITE_RELEASE } from "../../lib/release";

export const metadata = { title: "Pilot Terms and Safety" };

export default function TermsPage() {
  const environment = displayEnvironment(process.env.FAULTCITE_ENVIRONMENT);
  return <main className="policy-page"><article><span className="eyebrow">CONTROLLED PILOT</span><h1>Pilot terms and safety boundary</h1><p className="policy-lead">This page is a product-use summary, not a substitute for a signed pilot agreement reviewed by the parties.</p><h2>Authorized use</h2><p>FaultCite is invitation-only. Use is limited to the company workspace and role assigned to the signed-in account. Users must protect their account and immediately report access that appears incorrect.</p><h2>Maintenance safety</h2><ul><li>FaultCite records evidence, observations, review, and approval; it does not authorize a machine restart.</li><li>It does not replace lockout/tagout, employer safety programs, OEM procedures, qualified judgment, or required training.</li><li>Stop work and follow the employer’s escalation process whenever identity, energy state, safeguards, procedure, or authorization is uncertain.</li><li>Diagnostic guidance and citations remain withheld unless applicable page-level evidence has been reviewed and approved.</li></ul><h2>Pilot limitations</h2><p>This release has no subscription billing, predictive maintenance, machine telemetry, CMMS/ERP integration, or production uptime commitment. Pilot results must be measured from real approved company records; FaultCite does not claim proven downtime reduction or ROI.</p><h2>Written agreement required</h2><p>Price, scope, support, data ownership, retention, incident responsibilities, acceptance criteria, warranties, liability, and termination must be defined in the signed agreement before paid production use.</p></article><LegalLinks version={FAULTCITE_RELEASE} environment={environment} /></main>;
}
