import { eq } from "drizzle-orm";
import { getDb } from "../../../db";
import { auditLogs, caseEvents, caseEvidence, cases, invitations, machines, manuals, manualSources, memberships, organizations, pilotFeedback, users } from "../../../db/schema";
import { apiError, enforceRateLimit, isErrorResponse, requireApiContext, writeAudit } from "../../../lib/backend";

export async function GET() {
  const ctx = await requireApiContext(); if (isErrorResponse(ctx)) return ctx; if (ctx.role !== "owner") return apiError("Owner permission required", 403); const limited=await enforceRateLimit(ctx,"organization-export",3,3600);if(limited)return limited; const db = await getDb();
  const [[organization], machineRows, caseRows, eventRows, evidenceRows, manualRows, sourceRows, inviteRows, memberRows, feedbackRows, auditRows] = await Promise.all([
    db.select().from(organizations).where(eq(organizations.id, ctx.organizationId)).limit(1), db.select().from(machines).where(eq(machines.organizationId, ctx.organizationId)), db.select().from(cases).where(eq(cases.organizationId, ctx.organizationId)), db.select().from(caseEvents).where(eq(caseEvents.organizationId, ctx.organizationId)), db.select().from(caseEvidence).where(eq(caseEvidence.organizationId, ctx.organizationId)), db.select().from(manuals).where(eq(manuals.organizationId, ctx.organizationId)), db.select().from(manualSources).where(eq(manualSources.organizationId, ctx.organizationId)), db.select().from(invitations).where(eq(invitations.organizationId, ctx.organizationId)), db.select({ membershipId: memberships.id, role: memberships.role, active: memberships.active, email: users.email, displayName: users.displayName }).from(memberships).innerJoin(users, eq(memberships.userId, users.id)).where(eq(memberships.organizationId, ctx.organizationId)), db.select().from(pilotFeedback).where(eq(pilotFeedback.organizationId, ctx.organizationId)), db.select().from(auditLogs).where(eq(auditLogs.organizationId, ctx.organizationId)),
  ]);
  await writeAudit(ctx, "organization.exported", "organization", ctx.organizationId); const body=JSON.stringify({ exportedAt:new Date().toISOString(), organization, machines:machineRows, cases:caseRows, caseEvents:eventRows, evidenceMetadata:evidenceRows.map(evidence=>({ ...evidence, objectKey: undefined })), manuals:manualRows.map(manual=>({ ...manual, objectKey: undefined })), approvedManualSources:sourceRows, invitations:inviteRows.map(invite=>({ ...invite, tokenHash: undefined })), team:memberRows, pilotFeedback:feedbackRows, auditLog:auditRows },null,2);
  return new Response(body,{headers:{"content-type":"application/json; charset=utf-8","content-disposition":`attachment; filename="faultcite-company-export-${new Date().toISOString().slice(0,10)}.json"`,"cache-control":"private, no-store"}});
}
